### ISSUE TITLE
Should ECMAScript and Javascript be the same repo?

### ISSUE THREAD

**Issue by TheHandsomeCoder** [exercism/ecmascript#385]
It seems to differentiate between the two different versions. Most major browsers support ES6, The latest version of node has support too so in effect both are the same

**Comment by matthewmorgan** [comment]
@TheHandsomeCoder this issue comes up frequently!  We're currently discussing this, with a mind toward deprecating the EcmaScript track.  In fact, it was recently discussed here: https://github.com/exercism/ecmascript/issues/377

We're not planning on taking action on this immediately, but it is on our radar.
